version: '3' 
services:
  sqlectron-docker:
    image: openkbs/sqlectron-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlectron-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DISPLAY=${DISPLAY:-":0.0"}
    env_file:
      - ./.env
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/home/developer/workspace


